services:
  pingora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pingora
    restart: unless-stopped
    ports:
      - "8180:80"
    volumes:
      - ./pingora.toml:/etc/pingora.toml
    command: >
      /app/pingora -c /etc/pingora.toml
